# Google Cloud Build configuration for automated builds and deployments
# This file enables automatic builds when you push to your repository

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.cpu'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vtuhub-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vtuhub-api:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vtuhub-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vtuhub-api:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vtuhub-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vtuhub-api:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1,HF_HOME=/app/.cache/huggingface,HF_HUB_DISABLE_SYMLINKS_WARNING=1'

images:
  - 'gcr.io/$PROJECT_ID/vtuhub-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vtuhub-api:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

